[tool.poetry]
name = "speed-comparison"
version = "0.1.0"
description = "A Python I/O speed comparison"
authors = ["fabreteca"]


[tool.poetry.dependencies]
python = "^3.10"
requests = "2.28.2"
aiohttp = "3.8.4"
matplotlib = "3.7.1"